[package]
name = "gobang-rs"
version = "0.3.0"
authors = ["ts25504 <ts25504@gmail.com>"]

[dependencies]
chrono = "0.2"
clippy = {version = "*", optional = true}
quick-error = "1.1.0"

[features]
default = []

[lib]
name = "gobang"

[[bin]]
name = "gobang"
